# Generated by Django 5.2.6 on 2025-09-24 20:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fiat_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=9),
                ),
                ("public_key", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "private_key",
                    models.CharField(
                        blank=True, editable=False, max_length=256, null=True
                    ),
                ),
                (
                    "recipient_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Draw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="e.g., Nebula-1 Convergence", max_length=100
                    ),
                ),
                (
                    "prize_pool",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Prize pool in ASTRA",
                        max_digits=15,
                    ),
                ),
                (
                    "star_keys",
                    models.TextField(
                        help_text="JSON array of winning star keys [1,2,3,4,5,6]"
                    ),
                ),
                (
                    "nft_id",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 0.0.6861467",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "hcs_message_id",
                    models.CharField(
                        blank=True,
                        help_text="HCS receipt ID",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UPCOMING", "Upcoming"),
                            ("ACTIVE", "Active"),
                            ("ENDED", "Ended"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="UPCOMING",
                        max_length=10,
                    ),
                ),
                (
                    "draw_datetime",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("total_tickets_sold", models.PositiveIntegerField(default=0)),
                (
                    "total_prize_distributed",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "winning_ticket_serial",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "winner_wallet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="won_draws",
                        to="core.userwallet",
                    ),
                ),
            ],
            options={
                "ordering": ["-draw_datetime"],
            },
        ),
        migrations.CreateModel(
            name="ForgedKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "star_keys",
                    models.TextField(
                        help_text="JSON array of user's star keys [1,2,3,4,5,6]"
                    ),
                ),
                (
                    "hcs_message_id",
                    models.CharField(
                        blank=True,
                        help_text="HCS receipt ID",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        help_text="Unique mint serial number",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "nft_metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="NFT metadata storage"
                    ),
                ),
                (
                    "token_id",
                    models.CharField(
                        blank=True,
                        help_text="Hedera Token ID",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "draw",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forged_keys",
                        to="core.draw",
                    ),
                ),
                (
                    "user_wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forged_keys",
                        to="core.userwallet",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user_wallet", "draw"],
                        name="core_forged_user_wa_163cee_idx",
                    ),
                    models.Index(
                        fields=["serial_number"], name="core_forged_serial__e02ab7_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="core_forged_created_0c1f95_idx"
                    ),
                ],
                "unique_together": {("user_wallet", "draw", "serial_number")},
            },
        ),
        migrations.AddIndex(
            model_name="draw",
            index=models.Index(
                fields=["status", "draw_datetime"], name="core_draw_status_de8f87_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="draw",
            index=models.Index(fields=["uuid"], name="core_draw_uuid_d87213_idx"),
        ),
    ]
