# Generated by Django 5.2.6 on 2025-09-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forgedkey",
            name="star_keys",
            field=models.TextField(
                blank=True,
                help_text="JSON array of user's star keys [1,2,3,4,5,6]",
                null=True,
            ),
        ),
    ]
