# Generated by Django 5.2.6 on 2025-09-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_forgedkey_star_keys"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.CharField(max_length=1000)),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("trophy", "trophy"),
                            ("rocket", "rocket"),
                            ("key", "key"),
                            ("user-plus", "user-plus"),
                        ],
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
