# Generated by Django 5.2.6 on 2025-10-04 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "tournament_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily Tournament"),
                            ("weekly", "Weekly Championship"),
                            ("monthly", "Monthly Grand Prix"),
                            ("special", "Special Event"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "entry_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_prize_pool",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("max_players", models.IntegerField(default=16)),
                ("current_players", models.IntegerField(default=0)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("is_active", models.BooleanField(default=False)),
                ("is_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ArenaGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_id", models.CharField(max_length=20, unique=True)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("duel", "1v1 Duel"),
                            ("tournament", "Tournament"),
                            ("challenge", "Challenge"),
                            ("ranked", "Ranked Match"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting for Players"),
                            ("active", "Game Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("timeout", "Timeout"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                (
                    "stake_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "platform_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "winner_reward",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("current_player", models.IntegerField(default=1)),
                ("turn_number", models.IntegerField(default=1)),
                ("player1_energy", models.IntegerField(default=100)),
                ("player2_energy", models.IntegerField(default=100)),
                ("player1_time_remaining", models.IntegerField(default=180)),
                ("player2_time_remaining", models.IntegerField(default=180)),
                ("board_state", models.JSONField(default=dict)),
                ("move_history", models.JSONField(default=list)),
                ("victory_type", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "player1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arena_games_as_p1",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "player2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arena_games_as_p2",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arena_wins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ArenaPlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField(default=800)),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("protostar", "Protostar"),
                            ("nova", "Nova"),
                            ("galactic", "Galactic Player"),
                            ("stellar", "Stellar Expert"),
                            ("cosmic", "Cosmic Master"),
                            ("quantum", "Quantum Grandmaster"),
                        ],
                        default="protostar",
                        max_length=20,
                    ),
                ),
                ("games_played", models.IntegerField(default=0)),
                ("games_won", models.IntegerField(default=0)),
                ("win_streak", models.IntegerField(default=0)),
                ("max_win_streak", models.IntegerField(default=0)),
                (
                    "total_astra_won",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_astra_lost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arena_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Challenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stake_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "challenger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_challenges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "game",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="arena.arenagame",
                    ),
                ),
                (
                    "opponent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_challenges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TournamentParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.IntegerField(blank=True, null=True)),
                (
                    "prize_won",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="arena.tournament",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ArenaLeaderboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "season",
                    models.CharField(
                        choices=[
                            ("s1", "Season 1"),
                            ("s2", "Season 2"),
                            ("s3", "Season 3"),
                        ],
                        default="s1",
                        max_length=10,
                    ),
                ),
                ("position", models.IntegerField()),
                ("rating", models.IntegerField()),
                ("games_played", models.IntegerField()),
                ("win_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("astra_won", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["season", "position"],
                "unique_together": {("season", "player")},
            },
        ),
    ]
